FROM nvidia/cuda

# update source list
COPY ubuntu_16.04_sources_cn.list /etc/apt/sources.list
COPY dot.vimrc /root/.vimrc


# Install dependencies
RUN apt-get update -y
RUN apt-get install software-properties-common -y

# All packages (Will install much faster)
RUN apt-get install --no-install-recommends -y git cmake python-pip build-essential 

# update pip mirror
RUN mkdir /root/.config/pip
COPY pip.conf /root/.config/pip/pip.conf

# for python 3
RUN apt-get install python3-pip

# pytorch (Python 3.5, CUDA 9.0)
RUN pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp35-cp35m-linux_x86_64.whl 
RUN pip3 install torchvision


